Repository mttgermano/PLP-Guerras_Civis, pull requests merged in 2024-03, with the labels that each got.

#2 Front end
  web-app/package.json
  web-app/src/contexts/userContext.jsx
  web-app/src/css/main-page.css
  web-app/src/css/room.css
  web-app/src/css/user-auth.css
  web-app/src/pages/App.jsx
  web-app/src/pages/LoginPage.js
  web-app/src/pages/LoginPage.jsx
  web-app/src/pages/MainPage.jsx
  web-app/src/pages/RegistPage.jsx
  web-app/src/pages/RoomPage.jsx
  web-app/src/services/api.js
  web-app/src/services/mirage.js
Labels: enhancement

#3 adição da função para contar menção de jogadores na partida
  cabal/src/BotLogic.hs
  web-app/package-lock.json
Labels: enhancement

#4 new bot functions
  cabal/src/BotLogic.hs
  cabal/src/GameFunctions.hs
Labels: enhancement

#7 problemasResolvidos
  cabal/src/BotLogic.hs
  cabal/src/GameController.hs
  cabal/src/GameFunctions.hs
Labels: bug

#8 Bot
  cabal/src/BotLogic.hs
  cabal/src/GameFunctionsInit.hs
Labels: bug

#9 WaitingRoom Page
  web-app/src/css/room-home.css
  web-app/src/pages/App.jsx
  web-app/src/pages/RoomWaiting.jsx
Labels: enhancement

#10 try catch
  web-app/src/pages/LoginPage.jsx
  web-app/src/pages/RegistPage.jsx
Labels: bug

#11 update bot branch
  cabal/PLP-Guerras-Civis.cabal
  cabal/database/docker-compose.yml
  cabal/database/init.sql
  cabal/init.sh
  cabal/src/Controllers/GameController.hs
  cabal/src/Controllers/RoundController.hs
  cabal/src/Core/BackendServer.hs
  cabal/src/Core/DbFunctions.hs
  cabal/src/GameFunctionsInit.hs
  cabal/src/GameRoleFunctions.hs
  cabal/src/GameRoundController.hs
  cabal/src/GameRoundFunctions.hs
  cabal/src/GameUtils/BotLogic.hs
  cabal/src/GameUtils/ChatFunctions.hs
  cabal/src/GameUtils/GameFunctions.hs
  cabal/src/GameUtils/GameStartFunctions.hs
  cabal/src/GameUtils/RoleFunctions.hs
  cabal/src/GameUtils/RoundFunctions.hs
  cabal/src/LoginUtils/PlayerFunctions.hs
  cabal/src/LoginUtils/RoomFunctions.hs
  cabal/src/main.hs
  init.sh
  web-app/.gitignore
  web-app/package-lock.json
  web-app/src/css/room-home.css
  web-app/src/pages/App.jsx
  web-app/src/pages/LoginPage.jsx
  web-app/src/pages/RegistPage.jsx
  web-app/src/pages/RoomWaiting.jsx
Labels: bug, enhancement

#12 Bot Functions
  cabal/src/GameUtils/BotLogic.hs
  cabal/src/GameUtils/RoundFunctions.hs
Labels: enhancement

#13 Bot
  cabal/src/GameUtils/BotLogic.hs
  cabal/src/GameUtils/GameFunctions.hs
  cabal/src/GameUtils/RoleFunctions.hs
Labels: bug, documentation

#14 typos fix
  cabal/src/Core/BackendServer.hs
Labels: bug

#18 delete knoledge
  cabal/src/Game/BotLogic.hs
  cabal/src/Utils/Utils.hs
Labels: bug, enhancement

#19 Bot messages
  cabal/src/Game/BotLogic.hs
  cabal/src/Game/ChatFunctions.hs
  cabal/src/Game/GameFunctions.hs
  cabal/src/Game/RoleFunctions.hs
  cabal/src/Game/StartFunctions.hs
Labels: bug, documentation

#20 round result
  cabal/src/Controllers/RoundController.hs
  cabal/src/Game/BotLogic.hs
  cabal/src/Game/RoundFunctions.hs
Labels: bug, documentation

#22 Documentacao
  cabal/src/Controllers/GameController.hs
  cabal/src/Controllers/RoundController.hs
  cabal/src/Game/BotLogic.hs
  cabal/src/Game/RoleFunctions.hs
  cabal/src/Game/RoundFunctions.hs
  cabal/src/Utils/Utils.hs
Labels: bug, documentation

#23 functions until game start
  web-app/src/css/room-home.css
  web-app/src/pages/App.jsx
  web-app/src/pages/CreateRoom.jsx
  web-app/src/pages/LoginPage.jsx
  web-app/src/pages/RegistPage.jsx
  web-app/src/pages/RoomHome.jsx
  web-app/src/pages/RoomPage.jsx
  web-app/src/pages/RoomWaiting.jsx
Labels: bug, documentation

#24 botsRound its bugged
  cabal/src/Controllers/RoundController.hs
  cabal/src/Game/BotLogic.hs
  cabal/src/Game/RoleFunctions.hs
  cabal/src/Utils/Utils.hs
Labels: bug

#25 Bug fix
  cabal/src/Game/RoleFunctions.hs
  web-app/src/css/room-home.css
  web-app/src/pages/App.jsx
  web-app/src/pages/CreateRoom.jsx
  web-app/src/pages/LoginPage.jsx
  web-app/src/pages/RegistPage.jsx
  web-app/src/pages/RoomHome.jsx
  web-app/src/pages/RoomPage.jsx
  web-app/src/pages/RoomWaiting.jsx
Labels: bug

#26 Documentacao
  cabal/src/Controllers/RoundController.hs
  cabal/src/Game/BotLogic.hs
  cabal/src/Game/RoleFunctions.hs
  cabal/src/Utils/Utils.hs
Labels: bug, documentation

#27 Update
  cabal/src/Controllers/ApiController.hs
  cabal/src/Core/BackendServer.hs
Labels: bug, documentation
